apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAMESPACE}-postgres-config
data:
  # postgres
  POSTGRES_USER: '${POSTGRES_USER}'
  POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
  POSTGRES_DB: '${POSTGRES_DB}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAMESPACE}-hapi-config
data:
  # hapi
  HAPI_SERVER_PORT: '${HAPI_SERVER_PORT}'
  HAPI_SERVER_ADDRESS: '${HAPI_SERVER_ADDRESS}'
  HAPI_NETWORK_API: '${HAPI_NETWORK_API}'
  HAPI_NETWORK_CHAIN_ID: '${HAPI_NETWORK_CHAIN_ID}'
  HAPI_HASURA_URL: '${HAPI_HASURA_URL}'
  HAPI_HASURA_ADMIN_SECRET: '${HAPI_HASURA_ADMIN_SECRET}'
  HAPI_HYPERION_API: '${HAPI_HYPERION_API}'
  HAPI_HYPERION_START_AT: '${HAPI_HYPERION_START_AT}'
  HAPI_EXCHANGE_API: '${HAPI_EXCHANGE_API}'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${NAMESPACE}-hasura-config
data:
  # hasura
  HASURA_GRAPHQL_ENABLE_CONSOLE: '${HASURA_GRAPHQL_ENABLE_CONSOLE}'
  HASURA_GRAPHQL_DATABASE_URL: '${HASURA_GRAPHQL_DATABASE_URL}'
  HASURA_GRAPHQL_ADMIN_SECRET: '${HASURA_GRAPHQL_ADMIN_SECRET}'
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: '${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}'
  HASURA_GRAPHQL_ACTION_BASE_URL: '${HASURA_GRAPHQL_ACTION_BASE_URL}'
