apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${NAMESPACE}-hapi
  name: ${NAMESPACE}-hapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${NAMESPACE}-hapi
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${NAMESPACE}-hapi
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: ${DOCKER_REGISTRY}/${IMAGE_NAME_HAPI}:${VERSION}
          imagePullPolicy: 'Always'
          name: '${NAMESPACE}-hapi'
          envFrom:
            - configMapRef:
                name: ${NAMESPACE}-hapi-config
          ports:
            - containerPort: 9090
