apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${NAMESPACE}-hapi
  name: ${NAMESPACE}-hapi
spec:
  ports:
    - name: hapi
      port: 9090
      targetPort: 9090
  selector:
    app: ${NAMESPACE}-hapi
