apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${NAMESPACE}-hasura
  name: ${NAMESPACE}-hasura
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: hasura
      protocol: TCP
  selector:
    app: ${NAMESPACE}-hasura
